# NOTE: This application supports configuring via environment variables, but some variables can only be configured using this static file. This file must be included in the source to make it available to the Docker container - previous installations didn't use Docker and added this file manually. All other configuration variables should be managed using environment variables. getSettings.js has the list of variables. Note that variables used within Dockerfile need to be here, since it's not using env variables.

city_config="kerrokantasi-ui-turku"

# Object information about each layer to be used in wms layer array.
# layer_name acts like an id of an wms layer. Localized names are
# for users see and use to select desired layer.
# Example template for one layer object in wms_layer array:
# [[wms_layers]]
# layer_name=""
# name_fi=""
# name_sv=""
# name_en=""

[[wms_layers]]
layer_name="Asemakaava"
name_fi="Kaavakartta"
name_sv="Stadsplankarta"
name_en="Cityplan"

[[wms_layers]]
layer_name="Opaskartta"
name_fi="Opaskartta"
name_sv="Guidekarta"
name_en="Guidemap"

[[wms_layers]]
layer_name="Opaskartta mv"
name_fi="Opaskartta mv"
name_sv="Guidekarta s/v"
name_en="Guidemap b/w"

[[wms_layers]]
layer_name="Ilmakuva"
name_fi="Ilmakuva"
name_sv="Flygbild"
name_en="Air photo"

[[wms_layers]]
layer_name="Maastokartta"
name_fi="Maastokartta"
name_sv="Terrängkarta"
name_en="Terrain map"

[[wms_layers]]
layer_name="Turun kantakartta 1:1000"
name_fi="Turun kantakartta 1:1000"
name_sv="Turun kantakartta 1:1000"
name_en="Turun kantakartta 1:1000"
