name: Kerrokantasi CI

on:
  push:
    branches:
      - release
      - develop
  pull_request:
    branches:
      - '**'
      
jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        node-version: [14.x]
    steps:
    - uses: actions/checkout@master
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
        
    - name: Installing dependencies
      run: yarn
      
    - name: Running tests
      run: yarn test
